name: Sample Resources Test Deploy

on:
  pull_request:
    paths:
      - 'Makefile'
      - 'sample-resources/**'
  schedule:
    - cron: '50 3 * * *'

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Verify cluster status
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy sample resources
        run: make resources-deploy

      - name: Verify deployments
        run: |
          kubectl get all --all-namespaces

      - name: Cleanup
        if: always()
        run: make resources-destroy || true
